baseurl: ''
url: https://www.ruud.online

sass:
  sass_dir: assets/css

plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-assets
  - jekyll-target-blank

include:
  - _headers

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .idea
  - README.md
  - TODO.md
