baseurl: ''
url: https://www.ruud.online

markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-assets

include:
  - _headers

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - yarn.lock
  - package-lock.json
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .idea/
  - README.md
  - gulpfile.js
