baseurl: /
url: https://www.ruud.online

markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .idea/
