baseurl: ''
url: https://www.ruud.online

sass:
  sass_dir: assets/css
  style: compressed

assets:
  compression: true

defaults:
  - scope:
      path: "tools/**/*.*"
    values:
      sitemap: false
  - scope:
      path: "googlea1fd24277b5016b1.html"
    values:
      sitemap: false

plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-assets
  - jekyll-target-blank

include:
  - _headers
  - _redirects

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .idea
  - README.md
  - TODO.md
